version: '2.2'
services:
    app:
        build: app
    app2:
        build: app_2

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
    redis:
        image: redis:alpine


